random_seed: 1314  # null for no seed

dataset:
  name: Cifar10-LT
  kwargs: 
    im: 200

model:
  name: resnet34
  kwargs:
    pretrained: false

test:
  batch_size: 128

feature:
  path: feature/
  cam_layers: 'layer4'  # separate by comma. e.g., 'layer3, layer4'

checkpoint:
  load_checkpoint: 'checkpoints/phase_i/cifar10-LT_resnet34/im_200/model_epoch_0300.pt'
  
